config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "images#index"

  resources :images do
    resources :comments
  end

  resources :users do
    resources :images
  end

  resources :images do
    resources :tags
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :image

  validates :content, :presence => true

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :tags, dependent: :destroy
  has_many :tagged_users, through: :tags, source: :user
  has_attached_file :photo, :styles => { :large => "600x600#", :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  validates :caption, :presence => true

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
  has_many :comments
  has_many :tags
  has_many :tagged_images, through: :tags, dependent: :destroy, source: :image

  validates :email, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :authenticate_user!, except: [ :index, :show ]

  def index
    @images = Image.all
    render :index
  end

  def show
    @image = Image.find(params[:id])
    render :show
  end

  def new
    @image = current_user.images.new
    render :new
  end

  def create
    @image = current_user.images.new(image_params)
    @image.user = current_user
    if @image.save
      redirect_to images_path
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
    render :edit
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to images_path
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path
  end

private
  def image_params
    params.require(:image).permit(:caption, :photo)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def show
    @image = Image.find(params[:image_id])
    @tag = Tag.find(params[:id])
  end

  def new
    @image = Image.find(params[:image_id])
    @tag = @image.tags.new
  end

  def create
    @image = Image.find(params[:image_id])
    @tag = @image.tags.new(tag_params)
    @user = User.find_by_id(@tag.user_id)
      if @tag.save
        flash[:success] = "Tag recorded!"
        redirect_to image_path(@image)
      else
        flash[:alert] = "Tag unsuccessful, please try again!"
        render :new
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to image_path(@tag.image)
  end

private
  def tag_params
    params.require(:tag).permit(:user_id, :image_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [ :index, :show ]

  def show
    @user = User.find(params[:id])
    @images = @user.images
    render :show
  end

private
  def image_params
    params.require(:image).permit(:caption, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<%= render "layouts/errors", :object => @image %>

<%= form_for @image do |f| %>
  <%= f.label :caption %>
  <%= f.text_field :caption, :class => "form-control" %>
  <br>
  <%= f.label :photo %>
  <%= f.file_field :photo %>
  <%= f.submit :class => "btn btn-default"  %>
<% end %>

app/views/images/edit.html.erb
<% content_for(:title, "KATSTAGRAM | Edit") %>

<h1>Edit Image</h1>

<%= render "form" %>

app/views/images/index.html.erb
<% content_for(:title, "KATSTAGRAM | Index") %>

<div class="row">
  <div class="col-md-2 col-md-offset-5">
  <%= link_to "New Image", new_image_path, :class => "btn btn-default btn-lg" %>
  </div>
</div>

<br>
<div class="row">
  <% @images.each do |image| %>
  <div class="col-md-4">
    <%= link_to image.user.email, user_path(image.user) %>
    <%= link_to (image_tag image.photo.url(:medium)), image_path(image) %> <br>
    <span class="caption"><%= link_to image.caption, image_path(image) %></span>
  </div>
  <% end %>
</div>

app/views/images/new.html.erb
<% content_for(:title, "KATSTAGRAM | New") %>

<h2>New Image</h2>

<%= render "form" %>

app/views/images/show.html.erb
<% content_for(:title, "KATSTAGRAM | Show") %>

<div class="show-cat">
  <%= image_tag @image.photo(:large) %>
  <h2 class="caption">"<%= @image.caption %>"</h2>
</div>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if current_user %>
      <%= render "tags/new" %>
    <h4>tagged users</h4>
    <% if @image.tags.any? %>
      <% @image.tags.each do |tag| %>
      <%= link_to tag.user.email, image_tag_path(tag.image, tag), :method =>"delete", :class => "btn btn-default" %>
    <% end %>
  <% end %>
  <% else %>
  <p>Join to tag photos!</p>
  <% end %>
  <p>
  <% if current_user == nil %>
    <p>Reprimand: You Should Sign Up To Katstagram!</p>
  <% else %>
    <% if current_user.id == @image.user_id %>
      <%= link_to "Edit", edit_image_path(@image) %> <br>
      <%= link_to "Delete", image_path(@image),
                               :data => {:confirm => "You sure?",
                                         :method => "delete"} %>
    <% else %>
      <%= "You are not authorized to Edit or Delete this image"%>
    <% end %>
  <% end %>
  </p>

  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
  </head>
  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <% if user_signed_in? %>
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => "delete" %></li>
            <% else %>
              <li><%= link_to "Sign In", user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
      <h1>KATSTAGRAM</h1>
      <%= yield %>
    </div>

  </body>
</html>

app/views/tags/_new.html.erb
<%= form_for [@image, Tag.new] do |f| %>
  <%= f.label :tags %>
  <%= f.collection_select :user_id, User.all, :id, :email, include_blank: true %>
  <%= f.submit :class => "btn btn-default" %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<% content_for(:title, "KATSTAGRAM | Show") %>

<% content_for(:navbar) do %>
<li><a href="/">Katstagram Home</a></li>
<li>
<% if user_signed_in? %>
<%= link_to "Edit Account", edit_user_registration_path %>
<%= link_to "Sign Out", destroy_user_session_path, :method => "delete" %>
<% else %>
<%= link_to "Sign In", user_session_path %>
<% end %>
</li>
<% end %>


<h2 class="caption"><%= @user.email %></h2>

<ul>
  <% @images.each do |image| %>
    <%= link_to (image_tag image.photo(:medium)), image_path(image) %>
  <% end %>
</ul>